### ISSUE TITLE
Recent efforts to install fail

### ISSUE THREAD

**Issue by dper** [dsnopek/anki-sync-server#23]
If I install anki-sync-server and anki from source, and then I adjust the settings in anki so it tries to sync from my local server, sync does not work.  The client and server appear to start communicating but then it errors out.

If I run the server with `debug`, I get the following error.

````
INFO:root:CollectionThread[/home/d/src/anki-sync-server/collections/d/collection.anki2]: Running meta(*[], **{})
ERROR:root:CollectionThread[/home/d/src/anki-sync-server/collections/d/collection.anki2]: Unable to meta(*[], **{}): 'MediaManager' object has no attribute 'usn'
Traceback (most recent call last):
  File "/home/d/src/anki-sync-server/AnkiServer/threading.py", line 95, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/home/d/src/anki-sync-server/AnkiServer/collection.py", line 58, in execute
    ret = func(*args, **kw)
  File "/home/d/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 470, in runFunc
    result = func(**data)
  File "/home/d/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 75, in meta
    'musn': self.col.media.usn(),
AttributeError: 'MediaManager' object has no attribute 'usn'
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 37860)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/dist-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/dist-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/python2.7/dist-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/usr/lib/python2.7/dist-packages/paste/translogger.py", line 68, in __call__
    return self.application(environ, replacement_start_response)
  File "/usr/lib/python2.7/dist-packages/paste/urlmap.py", line 206, in __call__
    return app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 130, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 195, in call_func
    return self.func(req, *args, **kwargs)
  File "/home/d/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 476, in __call__
    result = thread.execute(runFunc)
  File "/home/d/src/anki-sync-server/AnkiServer/threading.py", line 76, in execute
    raise ret
AttributeError: 'MediaManager' object has no attribute 'usn'
----------------------------------------
````

In the client, at the same time, I get the generic pop-up error.

````
Syncing failed:
AnkiWeb encountered an error. Please try again in a few minutes, and if the problem persists, please file a bug report.
````

I assume that the client is too new of a version relative to the server.  But I don't know what to do about that.  Is this kind of thing the kind of thing that could be fixed with some screwing around?  Is it a gorilla of a problem?  Thanks for any thoughts or help!

**Comment by dsnopek** [comment]
I'd recommend using the version of Anki that's bundled with anki-sync-server (if you clone with `git clone --recursive` you'll get it). Unfortunately, I haven't had the time to keep up with recent Anki developement. Usually the changes necessary to make it work with newer versions aren't *that* difficult, but I haven't looked into it so I can't give any direction.

Also, the communication protocol changed in 2.0.27, for which there is already an open bug https://github.com/dsnopek/anki-sync-server/issues/16

**Comment by dper** [comment]
Ah, that makes sense.  So I try it again, using `anki-bundled` and adjusting `SYNC_URL` as necessary.  The same error messages as before still arise.  Let me know if I can help debug this.  It would be excellent to uncouple Anki from `ankiweb.net`.

**Comment by retracile** [comment]
I'm running into this same issue using the anki hash from anki-sync-server.  If there is any intro to anki internals; a pointer would be appreciated.

**Comment by retracile** [comment]
I think I figured out why I was getting this AttributeError; AnkiServer/__init__.py puts the system-installed Anki at the beginning of the python path 'sys.path.insert(0, "/usr/share/anki")'.  So it was attempting to use 2.0.32 from my distro instead of the bundled version.

**Comment by dper** [comment]
Unfortunately, the hard-coding of paths also happens in Anki itself.  (I suggested upstream that this was undesirable but was dismissed.)

**Comment by Akendo** [comment]
Any update on this ticket?

**Comment by Akendo** [comment]
You can close this issue since the https://github.com/dsnopek/anki-sync-server/issues/16 is closed it works fine!

**Comment by dsnopek** [comment]
Ok, closing! Thanks :-)
