### ISSUE TITLE
get "WindowsError: [Error 183] " while running ankiServer 2.0.6 on Paython27/Win7/64

### ISSUE THREAD

**Issue by ninja33** [dsnopek/anki-sync-server#44]
hi team:
I installed this package (2.0.6) by using easy_install, I successfully logon as username "test" in anki windows client, and anki client prompt me to upload/download all deck info for first time sync, I choose upload. then I got some errors in console.

so I just un-comment the line in production.ini for logging.conf, and change logging.conf to use file_handler to capture some info in server.log

seems something happened during file upload_opration
```
in operation_upload
os.rename(temp_db_path, session.get_collection_path())
WindowsError: [Error 183]
```
WindowsError: [Error 183] in python usually means you just can not rename that file because it already exists. so I double checked the whole process step by step.

- I ran "ankiserverctl.py adduser test" in windows command window below
```
E:\ankiserver>ankiserverctl.py adduser test
Enter password for test:
Password:
```
a sub folder named "test" under "E:\ankiserver\collections" created

- I ran "ankiserverctl.py" in windows console
```
E:\ankiserver>ankiserverctl.py debug
Starting server in PID 3836.
serving on http://127.0.0.1:27701
127.0.0.1 - - [28/Jun/2016:21:52:56 +0800] "POST /sync/meta HTTP/1.1" 200 108 "-" "Python-httplib2/0.7.7 (gzip)"
```
- back to anki client and input username "test" with password. 
- click top-right sync button in anki client, it prompt that for first time sync if I want to download or upload all deck? I choose upload. then error happened.

OK. I also tested several rounds in different scenario.I found it only happened in situation of full synchronization while **uploading**. in above failed uploading case, if I choose downloading first then create deck, make some notes and cards and upload, it will be successful.
but, after I made some "big change", like adding more fields and changing fields name, which may cause full synchronization. second time, I choose upload when anki client ask me which kind of full sync I want? error happened again,

here is the files and folder listed under username "test"
```
 E:\ankiserver\collections\test 
2016/06/28  22:37    <DIR>          .
2016/06/28  22:37    <DIR>          ..
2016/06/28  22:31            65,536 collection.anki2
2016/06/28  22:37                 0 collection.anki2-journal
2016/06/28  22:27            65,536 collection.anki2.tmp
2016/06/28  22:29    <DIR>          collection.media
2016/06/28  22:29             5,120 collection.media.db2
```
so, anybody can help have a look at this? thanks so much.

I also listed more information below for your reference.

**here is python version info on my PC**
`Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32`

**here is error message from server.log**

- 2016-06-28 21:23:24,130:root:INFO:CollectionThread[E:\ankiserver\collections\test\collection.anki2]: Starting...
- 2016-06-28 21:23:24,130:root:INFO:CollectionThread[E:\ankiserver\collections\test\collection.anki2]: Running meta(*[], **{})
- 2016-06-28 21:23:28,295:root:INFO:CollectionThread[E:\ankiserver\collections\test\collection.anki2]: Running operation_upload(*['SQLite format "
`lots of data, just truncated here`
{0in}\\n\\\\begin{document}\\n"}}{"1": {"name": "Default", "extendRev": 50, "usn": 0, "collapsed": false, "newToday": [0, 0], "timeToday": [0, 0], "dyn": 0, "extendNew": 10, "conf": 1, "revToday": [0, 0], "lrnToday": [0, 0], "id": 1, "mod": 1467120065, "desc": ""}}{"1": {"name": "Default", "replayq": true, "lapse": {"leechFails": 8, "minInt": 1, "delays": [10], "leechAction": 0, "mult": 0}, "rev": {"perDay": 100, "ivlFct": 1, "maxIvl": 36500, "minSpace": 1, "ease4": 1.3, "bury": true, "fuzz": 0.05}, "timer": 0, "dyn": false, "maxTaken": 60, "usn": 0, "new": {"separate": true, "delays": [1, 10], "perDay": 20, "ints": [1, 4, 7], "initialFactor": 2500, "bury": true, "order": 1}, "autoplay": true, "id": 1, "mod": 0}}{}', <AnkiServer.apps.sync_app.SyncUserSession object at 0x00000000032D8EB8>], **{}): [Error 183] 
Traceback (most recent call last):
  File "e:\python27\lib\site-packages\ankiserver-2.0.6-py2.7.egg\AnkiServer\threading.py", line 95, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "e:\python27\lib\site-packages\ankiserver-2.0.6-py2.7.egg\AnkiServer\collection.py", line 58, in execute
    ret = func(*args, **kw)
  File "e:\python27\lib\site-packages\ankiserver-2.0.6-py2.7.egg\AnkiServer\apps\sync_app.py", line 471, in operation_upload
    os.rename(temp_db_path, session.get_collection_path())
WindowsError: [Error 183] 

- 2016-06-28 21:23:51,505:paste.httpserver.ThreadPool:INFO:Shutting down threadpool
- 2016-06-28 21:23:51,520:paste.httpserver.ThreadPool:INFO:All workers stopped
- 2016-06-28 21:23:51,520:root:INFO:CollectionThread[E:\ankiserver\collections\test\collection.anki2]: Running _stop(*[], **{})
- 2016-06-28 21:23:51,522:root:INFO:CollectionThread[E:\ankiserver\collections\test\collection.anki2]: Stopped!
- 2016-06-28 21:23:51,522:paste.httpserver.ThreadPool:INFO:Shutting down threadpool
- 2016-06-28 21:23:51,523:paste.httpserver.ThreadPool:INFO:All workers stopped

**Comment by ninja33** [comment]
emm, I think I got the solution.
in python document [15.1. os — Miscellaneous operating system interfaces](https://docs.python.org/2/library/os.html), it mentioned.
```
os.rename(src, dst)
Rename the file or directory src to dst. If dst is a directory, OSError will be raised. On Unix, if dst exists and is a file, it will be replaced silently if the user has permission. The operation may fail on some Unix flavors if src and dst are on different filesystems. If successful, the renaming will be an atomic operation (this is a POSIX requirement). On Windows, if dst already exists, OSError will be raised even if it is a file; there may be no way to implement an atomic rename when dst names an existing file.
```

so, in windows environment, a quick fix could be remove prior to the rename
in sync_app.py line 471
```
        # Overwrite existing db.
        col.close()
        try:
            if os.name == 'nt':
                os.remove(session.get_collection_path())
            os.rename(temp_db_path, session.get_collection_path())
        finally:
            col.reopen()
```

**Comment by bosbyj** [comment]
Great job! It is working on my win8 platform.

**Comment by gabriellluz** [comment]
Your fix worked for me, too!! Thank you.
