### ISSUE TITLE
WindowsError: [Error 2] while debug

### ISSUE THREAD

**Issue by valuex** [dsnopek/anki-sync-server#53]
First, Thanks for building this wonderful project!
I've tried  this project's instruction on Win10 64bit with python 2.7 and get some error.
Kindly help to check the solution, thanks.
======Error Message========

Traceback (most recent call last):
  File "C:\Python27\Scripts\ankiserverctl.py", line 4, in <module>
    __import__('pkg_resources').run_script('ankiserver==2.0.6', 'ankiserverctl.py')
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\ankiserver-2.0.6-py2.7.egg\EGG-INFO\scripts\ankiserverctl.py", line 169, in <module>
    main()
  File "c:\python27\lib\site-packages\ankiserver-2.0.6-py2.7.egg\EGG-INFO\scripts\ankiserverctl.py", line 151, in main
    startsrv(sys.argv[2], True)
  File "c:\python27\lib\site-packages\ankiserver-2.0.6-py2.7.egg\EGG-INFO\scripts\ankiserverctl.py", line 42, in startsrv
    subprocess.call( ["paster", "serve", configpath], shell=False)
  File "C:\Python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by aikalant** [comment]
I am also getting a similar error. Can this project work with Windows at all?

**Comment by jdoe0** [comment]
Looks like the `paster` executable cannot be found. Is it in your `PATH`?

**Comment by aikalant** [comment]
Seems I fixed it. Had to use easy_install instead of pip and it is running fine. (Have not tested syncing yet though).

https://github.com/dsnopek/anki-sync-server/issues/40
