### ISSUE TITLE
mysyncserver.py

### ISSUE THREAD

**Issue by sanjie27** [dsnopek/anki-sync-server#78]

**Comment by sanjie27** [comment]
Thanks for your great work for anki-sync-server!

I create a folder named "ankisyc" in "\Anki2\addons21", and I create __init__.py which contains "import……" in "ankisyc". But when I try to sync in the client(Windows 10,python3), it doesn't work.
ps: I can sync successfully in my ankidroid.

The errors are as follows:
同步失败:
Traceback (most recent call last):
  File "aqt\sync.py", line 348, in run
  File "aqt\sync.py", line 373, in _sync
  File "anki\sync.py", line 574, in hostKey
  File "anki\sync.py", line 553, in req
  File "anki\sync.py", line 489, in syncURL
TypeError: not all arguments converted during string formatting

Thanks a lot for anyone's help!

**Comment by sanjie27** [comment]
On, I solve the problem by **_downgrade my anki from 2.1.6 to 2.0.5……_**

**Comment by wyrainer** [comment]
我也遇到了同样的问题，不知道怎么解决。
I have the same problem, don't know how to solve it.

我把addons文件内容改成：
import anki.sync
addr="http://192.168.3.32:27701/"
anki.sync.SYNC_BASE=addr+"%s"

不会报上面的错误了，但是一直提示我说用户名密码错。

**Comment by laiwenhui** [comment]
> 我也遇到了同样的问题，不知道怎么解决。
> I have the same problem, don't know how to solve it.
> 
> 我把addons文件内容改成：
> import anki.sync
> addr="http://192.168.3.32:27701/"
> anki.sync.SYNC_BASE=addr+"%s"
> 
> 不会报上面的错误了，但是一直提示我说用户名密码错。

请问问题有解决么，我也遇到同样的问题，谢谢！

**Comment by sanjie27** [comment]
我认为可能是版本的问题，开发者说的方法适用于anki2，不能用于anki2.1，可以降级试一下。
I think it might be caused by the version. Anki2 is suitable, but Anki2.1 not. You can have a try with Anki2, such as Anki2.0.5.
Good Luck!

**Comment by sunnysab** [comment]
我发现一个问题，阅读新旧版本的 anki\sync.py 代码，以及抓包，新旧版本中路径不太一样？
好像重新在 Windows 下编译 Anki 挺麻烦，算了…降级吧

I found that, there are some differences between the old and the new version, by capturing and reading codes of both versions.
It seems complicated that build Anki in Windows, giving up....Downgrade.

**Comment by ZJha** [comment]
I met the same issue under window 7. but under window10, it's ok. So I think it should be OS problem.
